### ISSUE TITLE
HTTPGet: HTTP Connection error

### ISSUE THREAD

**Issue by michalzubkowicz** [keskad/subget#25]
I've got error when I'm trying to download subtitles:

HTTPGet: HTTP Connection error, [Errno -5] No address associated with hostname
Segmentation fault (core dumped)

**Comment by keskad** [comment]
Hello,

Please could you specify which server you tried download from? (it's in right column in subtitles list)

It seems like a outdated plugin to me.

**Comment by michalzubkowicz** [comment]
It happens when I'm choosing subtitles (before download) full traceback:

17/06/2014 08:53:35, check_exists: napisy24.pl is temporary disabled because of required authentication changes
17/06/2014 08:53:35, HTTPGet: napisy.info/plugin/SzukajTytulow.php?sid=subget&t=House+Of+Cards+2013++01x12
17/06/2014 08:53:35, HTTPGet: api.allsubs.org/index.php?limit=20&search=House+Of+Cards+2013++01x12
17/06/2014 08:53:35, HTTPGet: napisy.info/plugin/SzukajTytulow.php?sid=subget&t=House+Of+Cards+2013++01x11
17/06/2014 08:53:35, check_exists: napisy24.pl is temporary disabled because of required authentication changes
17/06/2014 08:53:35, HTTPGet: api.allsubs.org/index.php?limit=20&search=House+Of+Cards+2013++01x11
17/06/2014 08:53:35, check_exists: napisy24.pl is temporary disabled because of required authentication changes
17/06/2014 08:53:35, HTTPGet: api.allsubs.org/index.php?limit=20&search=House+Of+Cards+2013++01x09
 17/06/2014 08:53:35, HTTPGet: napisy.info/plugin/SzukajTytulow.php?sid=subget&t=House+Of+Cards+2013++01x09
17/06/2014 08:53:35, check_exists: napisy24.pl is temporary disabled because of required authentication changes
17/06/2014 08:53:35, HTTPGet: napisy.info/plugin/SzukajTytulow.php?sid=subget&t=House+Of+Cards+2013++01x07
17/06/2014 08:53:35, HTTPGet: api.allsubs.org/index.php?limit=20&search=House+Of+Cards+2013++01x07
17/06/2014 08:53:35, check_exists: napisy24.pl is temporary disabled because of required authentication changes
17/06/2014 08:53:35, HTTPGet: napisy.info/plugin/SzukajTytulow.php?sid=subget&t=House+Of+Cards+2013++01x08
17/06/2014 08:53:35, HTTPGet: api.allsubs.org/index.php?limit=20&search=House+Of+Cards+2013++01x08
17/06/2014 08:53:35, check_exists: napisy24.pl is temporary disabled because of required authentication changes
17/06/2014 08:53:35, HTTPGet: api.allsubs.org/index.php?limit=20&search=House+Of+Cards+2013++01x06
 17/06/2014 08:53:35, HTTPGet: napisy.info/plugin/SzukajTytulow.php?sid=subget&t=House+Of+Cards+2013++01x06
17/06/2014 08:53:35, HTTPGet: napisy.info/plugin/SzukajTytulow.php?sid=subget&t=House+Of+Cards+2013++01x10
17/06/2014 08:53:35, check_exists: napisy24.pl is temporary disabled because of required authentication changes
17/06/2014 08:53:35, HTTPGet: api.allsubs.org/index.php?limit=20&search=House+Of+Cards+2013++01x10
17/06/2014 08:53:35, check_exists: napisy24.pl is temporary disabled because of required authentication changes
17/06/2014 08:53:35, HTTPGet: api.allsubs.org/index.php?limit=20&search=House+Of+Cards+2013++01x13
17/06/2014 08:53:35, HTTPGet: napisy.info/plugin/SzukajTytulow.php?sid=subget&t=House+Of+Cards+2013++01x13
Exception in thread Thread-29:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in **bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "/usr/local/bin/subget", line 609, in GTKCheckForSubtitles
    Results = self.plugins[Plugin].instance.download_list(self.files).output()
  File "/usr/local/lib/python2.7/dist-packages/subgetlib/opensubtitles.py", line 71, in download_list
    return self.searchSubtitles(Files, resultsClass)
  File "/usr/local/lib/python2.7/dist-packages/subgetlib/opensubtitles.py", line 82, in searchSubtitles
    subtitlesList = self.server.SearchSubtitles(token, searchList)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in __call**
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1289, in single_request
    self.send_request(h, handler, request_body)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1391, in send_request
    connection.putrequest("POST", handler, skip_accept_encoding=True)
  File "/usr/lib/python2.7/httplib.py", line 871, in putrequest
    raise CannotSendRequest()
CannotSendRequest

17/06/2014 08:53:36, HTTPGet: HTTP Connection error, [Errno -5] No address associated with hostname
17/06/2014 08:53:36, HTTPGet: HTTP Connection error, [Errno -5] No address associated with hostname
17/06/2014 08:53:36, HTTPGet: HTTP Connection error, [Errno -5] No address associated with hostname
17/06/2014 08:53:36, HTTPGet: HTTP Connection error, [Errno -5] No address associated with hostname
17/06/2014 08:53:36, HTTPGet: HTTP Connection error, [Errno -5] No address associated with hostname
17/06/2014 08:53:36, HTTPGet: HTTP Connection error, [Errno -5] No address associated with hostname
 17/06/2014 08:53:36, HTTPGet: HTTP Connection error, [Errno -5] No address associated with hostname
Exception in thread Thread-45:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in **bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "/usr/local/bin/subget", line 609, in GTKCheckForSubtitles
    Results = self.plugins[Plugin].instance.download_list(self.files).output()
  File "/usr/local/lib/python2.7/dist-packages/subgetlib/opensubtitles.py", line 71, in download_list
    return self.searchSubtitles(Files, resultsClass)
  File "/usr/local/lib/python2.7/dist-packages/subgetlib/opensubtitles.py", line 82, in searchSubtitles
    subtitlesList = self.server.SearchSubtitles(token, searchList)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in __call**
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1294, in single_request
    response = h.getresponse(buffering=True)
  File "/usr/lib/python2.7/httplib.py", line 1033, in getresponse
    raise ResponseNotReady()
ResponseNotReady

17/06/2014 08:53:36, HTTPGet: HTTP Connection error, [Errno -5] No address associated with hostname
Segmentation fault (core dumped)

**Comment by keskad** [comment]
On Mon, 16 Jun 2014 23:55:13 -0700
Michał Zubkowicz notifications@github.com wrote:

> It happens when I'm choosing subtitles (before download) full traceback:
> 
> 17/06/2014 08:53:35, check_exists: napisy24.pl is temporary disabled because of required authentication changes
> 17/06/2014 08:53:35, HTTPGet: napisy.info/plugin/SzukajTytulow.php?sid=subget&t=House+Of+Cards+2013++01x12
> 17/06/2014 08:53:35, HTTPGet: api.allsubs.org/index.php?limit=20&search=House+Of+Cards+2013++01x12
> 17/06/2014 08:53:35, HTTPGet: napisy.info/plugin/SzukajTytulow.php?sid=subget&t=House+Of+Cards+2013++01x11
> 17/06/2014 08:53:35, check_exists: napisy24.pl is temporary disabled because of required authentication changes
> 17/06/2014 08:53:35, HTTPGet: api.allsubs.org/index.php?limit=20&search=House+Of+Cards+2013++01x11
> 17/06/2014 08:53:35, check_exists: napisy24.pl is temporary disabled because of required authentication changes
> 17/06/2014 08:53:35, HTTPGet: api.allsubs.org/index.php?limit=20&search=House+Of+Cards+2013++01x09
>  17/06/2014 08:53:35, HTTPGet: napisy.info/plugin/SzukajTytulow.php?sid=subget&t=House+Of+Cards+2013++01x09
> 17/06/2014 08:53:35, check_exists: napisy24.pl is temporary disabled because of required authentication changes
> 17/06/2014 08:53:35, HTTPGet: napisy.info/plugin/SzukajTytulow.php?sid=subget&t=House+Of+Cards+2013++01x07
> 17/06/2014 08:53:35, HTTPGet: api.allsubs.org/index.php?limit=20&search=House+Of+Cards+2013++01x07
> 17/06/2014 08:53:35, check_exists: napisy24.pl is temporary disabled because of required authentication changes
> 17/06/2014 08:53:35, HTTPGet: napisy.info/plugin/SzukajTytulow.php?sid=subget&t=House+Of+Cards+2013++01x08
> 17/06/2014 08:53:35, HTTPGet: api.allsubs.org/index.php?limit=20&search=House+Of+Cards+2013++01x08
> 17/06/2014 08:53:35, check_exists: napisy24.pl is temporary disabled because of required authentication changes
> 17/06/2014 08:53:35, HTTPGet: api.allsubs.org/index.php?limit=20&search=House+Of+Cards+2013++01x06
>  17/06/2014 08:53:35, HTTPGet: napisy.info/plugin/SzukajTytulow.php?sid=subget&t=House+Of+Cards+2013++01x06
> 17/06/2014 08:53:35, HTTPGet: napisy.info/plugin/SzukajTytulow.php?sid=subget&t=House+Of+Cards+2013++01x10
> 17/06/2014 08:53:35, check_exists: napisy24.pl is temporary disabled because of required authentication changes
> 17/06/2014 08:53:35, HTTPGet: api.allsubs.org/index.php?limit=20&search=House+Of+Cards+2013++01x10
> 17/06/2014 08:53:35, check_exists: napisy24.pl is temporary disabled because of required authentication changes
> 17/06/2014 08:53:35, HTTPGet: api.allsubs.org/index.php?limit=20&search=House+Of+Cards+2013++01x13
> 17/06/2014 08:53:35, HTTPGet: napisy.info/plugin/SzukajTytulow.php?sid=subget&t=House+Of+Cards+2013++01x13
> Exception in thread Thread-29:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/threading.py", line 810, in **bootstrap_inner
>     self.run()
>   File "/usr/lib/python2.7/threading.py", line 763, in run
>     self.__target(_self.__args, *_self.__kwargs)
>   File "/usr/local/bin/subget", line 609, in GTKCheckForSubtitles
>     Results = self.plugins[Plugin].instance.download_list(self.files).output()
>   File "/usr/local/lib/python2.7/dist-packages/subgetlib/opensubtitles.py", line 71, in download_list
>     return self.searchSubtitles(Files, resultsClass)
>   File "/usr/local/lib/python2.7/dist-packages/subgetlib/opensubtitles.py", line 82, in searchSubtitles
>     subtitlesList = self.server.SearchSubtitles(token, searchList)
>   File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in __call**
>     return self.__send(self.__name, args)
>   File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
>     verbose=self.__verbose
>   File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
>     return self.single_request(host, handler, request_body, verbose)
>   File "/usr/lib/python2.7/xmlrpclib.py", line 1289, in single_request
>     self.send_request(h, handler, request_body)
>   File "/usr/lib/python2.7/xmlrpclib.py", line 1391, in send_request
>     connection.putrequest("POST", handler, skip_accept_encoding=True)
>   File "/usr/lib/python2.7/httplib.py", line 871, in putrequest
>     raise CannotSendRequest()
> CannotSendRequest
> 
> 17/06/2014 08:53:36, HTTPGet: HTTP Connection error, [Errno -5] No address associated with hostname
> 17/06/2014 08:53:36, HTTPGet: HTTP Connection error, [Errno -5] No address associated with hostname
> 17/06/2014 08:53:36, HTTPGet: HTTP Connection error, [Errno -5] No address associated with hostname
> 17/06/2014 08:53:36, HTTPGet: HTTP Connection error, [Errno -5] No address associated with hostname
> 17/06/2014 08:53:36, HTTPGet: HTTP Connection error, [Errno -5] No address associated with hostname
> 17/06/2014 08:53:36, HTTPGet: HTTP Connection error, [Errno -5] No address associated with hostname
>  17/06/2014 08:53:36, HTTPGet: HTTP Connection error, [Errno -5] No address associated with hostname
> Exception in thread Thread-45:
> Traceback (most recent call last):
>   File "/usr/lib/python2.7/threading.py", line 810, in **bootstrap_inner
>     self.run()
>   File "/usr/lib/python2.7/threading.py", line 763, in run
>     self.__target(_self.__args, *_self.__kwargs)
>   File "/usr/local/bin/subget", line 609, in GTKCheckForSubtitles
>     Results = self.plugins[Plugin].instance.download_list(self.files).output()
>   File "/usr/local/lib/python2.7/dist-packages/subgetlib/opensubtitles.py", line 71, in download_list
>     return self.searchSubtitles(Files, resultsClass)
>   File "/usr/local/lib/python2.7/dist-packages/subgetlib/opensubtitles.py", line 82, in searchSubtitles
>     subtitlesList = self.server.SearchSubtitles(token, searchList)
>   File "/usr/lib/python2.7/xmlrpclib.py", line 1224, in __call**
>     return self.__send(self.__name, args)
>   File "/usr/lib/python2.7/xmlrpclib.py", line 1578, in __request
>     verbose=self.__verbose
>   File "/usr/lib/python2.7/xmlrpclib.py", line 1264, in request
>     return self.single_request(host, handler, request_body, verbose)
>   File "/usr/lib/python2.7/xmlrpclib.py", line 1294, in single_request
>     response = h.getresponse(buffering=True)
>   File "/usr/lib/python2.7/httplib.py", line 1033, in getresponse
>     raise ResponseNotReady()
> ResponseNotReady
> 
> 17/06/2014 08:53:36, HTTPGet: HTTP Connection error, [Errno -5] No address associated with hostname
> Segmentation fault (core dumped)
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/webnull/subget/issues/25#issuecomment-46273203

I think that napisy.info plugin is not working, try to disable it and tell me if it helped.
Anyway its not normall that it Segfaulted. It should catch exception and work normally.

**Comment by michalzubkowicz** [comment]
With disabled napisy.info plugin it's not segfaulting, but still crashing:

```
17/06/2014 11:48:00, addSubtitlesRow: ?.xpm icon does not exists, using unknown.xpm
17/06/2014 11:48:00, GTKCheckForSubtitles: [plugin:thesubdb] found subtitles - movie.2013.S01E13.720p.BluRay.x264.anoXmous.mp4 (hash)
17/06/2014 11:48:00, addSubtitlesRow: ?.xpm icon does not exists, using unknown.xpm
17/06/2014 11:48:00, GTKCheckForSubtitles: [plugin:thesubdb] found subtitles - movie.2013.S01E13.720p.BluRay.x264.anoXmous.mp4 (hash)
[plugin:thesubdb] Not found for /home/q/Torrent/movie.2013.S01.Season.1.720p.BluRay.x264.anoXmous/movie.2013.S01E06.720p.BluRay.x264.anoXmous.mp4 in de language.
17/06/2014 11:48:00, addSubtitlesRow: ?.xpm icon does not exists, using unknown.xpm
17/06/2014 11:48:00, GTKCheckForSubtitles: [plugin:thesubdb] found subtitles - movie.2013.S01E06.720p.BluRay.x264.anoXmous.mp4 (hash)
17/06/2014 11:48:00, addSubtitlesRow: ?.xpm icon does not exists, using unknown.xpm
17/06/2014 11:48:00, GTKCheckForSubtitles: [plugin:thesubdb] found subtitles - movie.2013.S01E06.720p.BluRay.x264.anoXmous.mp4 (hash)
[plugin:thesubdb] Not found for /home/q/Torrent/movie.2013.S01.Season.1.720p.BluRay.x264.anoXmous/movie.2013.S01E12.720p.BluRay.x264.anoXmous.mp4 in de language.
17/06/2014 11:48:00, addSubtitlesRow: ?.xpm icon does not exists, using unknown.xpm
17/06/2014 11:48:00, GTKCheckForSubtitles: [plugin:thesubdb] found subtitles - movie.2013.S01E12.720p.BluRay.x264.anoXmous.mp4 (hash)
17/06/2014 11:48:00, addSubtitlesRow: ?.xpm icon does not exists, using unknown.xpm
17/06/2014 11:48:00, GTKCheckForSubtitles: [plugin:thesubdb] found subtitles - movie.2013.S01E12.720p.BluRay.x264.anoXmous.mp4 (hash)
[plugin:thesubdb] Not found for /home/q/Torrent/movie.2013.S01.Season.1.720p.BluRay.x264.anoXmous/movie.2013.S01E08.720p.BluRay.x264.anoXmous.mp4 in de language.
17/06/2014 11:48:00, addSubtitlesRow: ?.xpm icon does not exists, using unknown.xpm
17/06/2014 11:48:00, GTKCheckForSubtitles: [plugin:thesubdb] found subtitles - movie.2013.S01E08.720p.BluRay.x264.anoXmous.mp4 (hash)
17/06/2014 11:48:00, addSubtitlesRow: ?.xpm icon does not exists, using unknown.xpm
17/06/2014 11:48:00, GTKCheckForSubtitles: [plugin:thesubdb] found subtitles - movie.2013.S01E08.720p.BluRay.x264.anoXmous.mp4 (hash)
[plugin:thesubdb] Not found for /home/q/Torrent/movie.2013.S01.Season.1.720p.BluRay.x264.anoXmous/movie.2013.S01E10.720p.BluRay.x264.anoXmous.mp4 in de language.
17/06/2014 11:48:00, addSubtitlesRow: ?.xpm icon does not exists, using unknown.xpm
17/06/2014 11:48:00, GTKCheckForSubtitles: [plugin:thesubdb] found subtitles - movie.2013.S01E10.720p.BluRay.x264.anoXmous.mp4 (hash)
17/06/2014 11:48:00, addSubtitlesRow: ?.xpm icon does not exists, using unknown.xpm
17/06/2014 11:48:00, GTKCheckForSubtitles: [plugin:thesubdb] found subtitles - movie.2013.S01E10.720p.BluRay.x264.anoXmous.mp4 (hash)
[plugin:thesubdb] Not found for /home/q/Torrent/movie.2013.S01.Season.1.720p.BluRay.x264.anoXmous/movie.2013.S01E09.720p.BluRay.x264.anoXmous.mp4 in de language.
17/06/2014 11:48:00, addSubtitlesRow: ?.xpm icon does not exists, using unknown.xpm
[plugin:thesubdb] Not found for /home/q/Torrent/movie.2013.S01.Season.1.720p.BluRay.x264.anoXmous/movie.2013.S01E07.720p.BluRay.x264.anoXmous.mp4 in de language.
17/06/2014 11:48:00, GTKCheckForSubtitles: [plugin:thesubdb] found subtitles - movie.2013.S01E09.720p.BluRay.x264.anoXmous.mp4 (hash)
17/06/2014 11:48:00, addSubtitlesRow: ?.xpm icon does not exists, using unknown.xpm
17/06/2014 11:48:00, addSubtitlesRow: ?.xpm icon does not exists, using unknown.xpm
17/06/2014 11:48:00, GTKCheckForSubtitles: [plugin:thesubdb] found subtitles - movie.2013.S01E09.720p.BluRay.x264.anoXmous.mp4 (hash)
17/06/2014 11:48:00, GTKCheckForSubtitles: [plugin:thesubdb] found subtitles - movie.2013.S01E07.720p.BluRay.x264.anoXmous.mp4 (hash)
17/06/2014 11:48:00, addSubtitlesRow: ?.xpm icon does not exists, using unknown.xpm
17/06/2014 11:48:00, GTKCheckForSubtitles: [plugin:thesubdb] found subtitles - movie.2013.S01E07.720p.BluRay.x264.anoXmous.mp4 (hash)
[plugin:thesubdb] Not found for /home/q/Torrent/movie.2013.S01.Season.1.720p.BluRay.x264.anoXmous/movie.2013.S01E11.720p.BluRay.x264.anoXmous.mp4 in de language.
17/06/2014 11:48:00, addSubtitlesRow: ?.xpm icon does not exists, using unknown.xpm
17/06/2014 11:48:00, GTKCheckForSubtitles: [plugin:thesubdb] found subtitles - movie.2013.S01E11.720p.BluRay.x264.anoXmous.mp4 (hash)
17/06/2014 11:48:00, addSubtitlesRow: ?.xpm icon does not exists, using unknown.xpm
17/06/2014 11:48:00, GTKCheckForSubtitles: [plugin:thesubdb] found subtitles - movie.2013.S01E11.720p.BluRay.x264.anoXmous.mp4 (hash)
17/06/2014 11:48:06, HTTPGet: HTTP Connection error, timed out
17/06/2014 11:48:06, HTTPGet: HTTP Connection error, timed out
17/06/2014 11:48:06, HTTPGet: HTTP Connection error, timed out
17/06/2014 11:48:06, HTTPGet: HTTP Connection error, timed out
17/06/2014 11:48:06, HTTPGet: HTTP Connection error, timed out
17/06/2014 11:48:06, HTTPGet: HTTP Connection error, timed out
17/06/2014 11:48:06, HTTPGet: HTTP Connection error, timed out
17/06/2014 11:48:06, HTTPGet: HTTP Connection error, timed out
```

**Comment by keskad** [comment]
On Tue, 17 Jun 2014 02:51:03 -0700
Michał Zubkowicz notifications@github.com wrote:

> With disabled napisy.info plugin it's not segfaulting, but still crashing:
> 
> ```
> 17/06/2014 11:48:00, addSubtitlesRow: ?.xpm icon does not exists, using unknown.xpm
> 17/06/2014 11:48:00, GTKCheckForSubtitles: [plugin:thesubdb] found subtitles - movie.2013.S01E13.720p.BluRay.x264.anoXmous.mp4 (hash)
> 17/06/2014 11:48:00, addSubtitlesRow: ?.xpm icon does not exists, using unknown.xpm
> 17/06/2014 11:48:00, GTKCheckForSubtitles: [plugin:thesubdb] found subtitles - movie.2013.S01E13.720p.BluRay.x264.anoXmous.mp4 (hash)
> [plugin:thesubdb] Not found for /home/q/Torrent/movie.2013.S01.Season.1.720p.BluRay.x264.anoXmous/movie.2013.S01E06.720p.BluRay.x264.anoXmous.mp4 in de language.
> 17/06/2014 11:48:00, addSubtitlesRow: ?.xpm icon does not exists, using unknown.xpm
> 17/06/2014 11:48:00, GTKCheckForSubtitles: [plugin:thesubdb] found subtitles - movie.2013.S01E06.720p.BluRay.x264.anoXmous.mp4 (hash)
> 17/06/2014 11:48:00, addSubtitlesRow: ?.xpm icon does not exists, using unknown.xpm
> 17/06/2014 11:48:00, GTKCheckForSubtitles: [plugin:thesubdb] found subtitles - movie.2013.S01E06.720p.BluRay.x264.anoXmous.mp4 (hash)
> [plugin:thesubdb] Not found for /home/q/Torrent/movie.2013.S01.Season.1.720p.BluRay.x264.anoXmous/movie.2013.S01E12.720p.BluRay.x264.anoXmous.mp4 in de language.
> 17/06/2014 11:48:00, addSubtitlesRow: ?.xpm icon does not exists, using unknown.xpm
> 17/06/2014 11:48:00, GTKCheckForSubtitles: [plugin:thesubdb] found subtitles - movie.2013.S01E12.720p.BluRay.x264.anoXmous.mp4 (hash)
> 17/06/2014 11:48:00, addSubtitlesRow: ?.xpm icon does not exists, using unknown.xpm
> 17/06/2014 11:48:00, GTKCheckForSubtitles: [plugin:thesubdb] found subtitles - movie.2013.S01E12.720p.BluRay.x264.anoXmous.mp4 (hash)
> [plugin:thesubdb] Not found for /home/q/Torrent/movie.2013.S01.Season.1.720p.BluRay.x264.anoXmous/movie.2013.S01E08.720p.BluRay.x264.anoXmous.mp4 in de language.
> 17/06/2014 11:48:00, addSubtitlesRow: ?.xpm icon does not exists, using unknown.xpm
> 17/06/2014 11:48:00, GTKCheckForSubtitles: [plugin:thesubdb] found subtitles - movie.2013.S01E08.720p.BluRay.x264.anoXmous.mp4 (hash)
> 17/06/2014 11:48:00, addSubtitlesRow: ?.xpm icon does not exists, using unknown.xpm
> 17/06/2014 11:48:00, GTKCheckForSubtitles: [plugin:thesubdb] found subtitles - movie.2013.S01E08.720p.BluRay.x264.anoXmous.mp4 (hash)
> [plugin:thesubdb] Not found for /home/q/Torrent/movie.2013.S01.Season.1.720p.BluRay.x264.anoXmous/movie.2013.S01E10.720p.BluRay.x264.anoXmous.mp4 in de language.
> 17/06/2014 11:48:00, addSubtitlesRow: ?.xpm icon does not exists, using unknown.xpm
> 17/06/2014 11:48:00, GTKCheckForSubtitles: [plugin:thesubdb] found subtitles - movie.2013.S01E10.720p.BluRay.x264.anoXmous.mp4 (hash)
> 17/06/2014 11:48:00, addSubtitlesRow: ?.xpm icon does not exists, using unknown.xpm
> 17/06/2014 11:48:00, GTKCheckForSubtitles: [plugin:thesubdb] found subtitles - movie.2013.S01E10.720p.BluRay.x264.anoXmous.mp4 (hash)
> [plugin:thesubdb] Not found for /home/q/Torrent/movie.2013.S01.Season.1.720p.BluRay.x264.anoXmous/movie.2013.S01E09.720p.BluRay.x264.anoXmous.mp4 in de language.
> 17/06/2014 11:48:00, addSubtitlesRow: ?.xpm icon does not exists, using unknown.xpm
> [plugin:thesubdb] Not found for /home/q/Torrent/movie.2013.S01.Season.1.720p.BluRay.x264.anoXmous/movie.2013.S01E07.720p.BluRay.x264.anoXmous.mp4 in de language.
> 17/06/2014 11:48:00, GTKCheckForSubtitles: [plugin:thesubdb] found subtitles - movie.2013.S01E09.720p.BluRay.x264.anoXmous.mp4 (hash)
> 17/06/2014 11:48:00, addSubtitlesRow: ?.xpm icon does not exists, using unknown.xpm
> 17/06/2014 11:48:00, addSubtitlesRow: ?.xpm icon does not exists, using unknown.xpm
> 17/06/2014 11:48:00, GTKCheckForSubtitles: [plugin:thesubdb] found subtitles - movie.2013.S01E09.720p.BluRay.x264.anoXmous.mp4 (hash)
> 17/06/2014 11:48:00, GTKCheckForSubtitles: [plugin:thesubdb] found subtitles - movie.2013.S01E07.720p.BluRay.x264.anoXmous.mp4 (hash)
> 17/06/2014 11:48:00, addSubtitlesRow: ?.xpm icon does not exists, using unknown.xpm
> 17/06/2014 11:48:00, GTKCheckForSubtitles: [plugin:thesubdb] found subtitles - movie.2013.S01E07.720p.BluRay.x264.anoXmous.mp4 (hash)
> [plugin:thesubdb] Not found for /home/q/Torrent/movie.2013.S01.Season.1.720p.BluRay.x264.anoXmous/movie.2013.S01E11.720p.BluRay.x264.anoXmous.mp4 in de language.
> 17/06/2014 11:48:00, addSubtitlesRow: ?.xpm icon does not exists, using unknown.xpm
> 17/06/2014 11:48:00, GTKCheckForSubtitles: [plugin:thesubdb] found subtitles - movie.2013.S01E11.720p.BluRay.x264.anoXmous.mp4 (hash)
> 17/06/2014 11:48:00, addSubtitlesRow: ?.xpm icon does not exists, using unknown.xpm
> 17/06/2014 11:48:00, GTKCheckForSubtitles: [plugin:thesubdb] found subtitles - movie.2013.S01E11.720p.BluRay.x264.anoXmous.mp4 (hash)
> 17/06/2014 11:48:06, HTTPGet: HTTP Connection error, timed out
> 17/06/2014 11:48:06, HTTPGet: HTTP Connection error, timed out
> 17/06/2014 11:48:06, HTTPGet: HTTP Connection error, timed out
> 17/06/2014 11:48:06, HTTPGet: HTTP Connection error, timed out
> 17/06/2014 11:48:06, HTTPGet: HTTP Connection error, timed out
> 17/06/2014 11:48:06, HTTPGet: HTTP Connection error, timed out
> 17/06/2014 11:48:06, HTTPGet: HTTP Connection error, timed out
> 17/06/2014 11:48:06, HTTPGet: HTTP Connection error, timed out
> 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/webnull/subget/issues/25#issuecomment-46287517
> ```

It's just exiting or what?

**Comment by michalzubkowicz** [comment]
Just Exiting. I've checked again and it's also with segfault:
Segmentation fault (core dumped)
Maybe it would be useful. My Python version is 2.7.6

**Comment by keskad** [comment]
Subget was tested on this Python version and worked fine.
I think that this segfault caused by mistake in any python library.
What's your operating system?

Can you post output of `strace subget`? (but please paste it on external pastebin server)

It can be done via `strace subget > /tmp/log` - please upload /tmp/log to external server.

Currently I don't want to make big changes to Subget as after year of coding and getting experience I understood that Subget's code quality is very low. I have to find time to rewrite it to objective programming, Qt5 and Panthera Desktop Framework.
